# Available command prefixes.
# Any message that starts with these characters will be interpreted as a command.
prefixes:
  - '.'
  - '!'
messages:
  # Maximum allowed length of the tag list before being cut off.
  max_tag_length: 512
  # Maximum allowed length of the image description before being cut off.
  max_desc_length: 256
# Discord-specific configuration
discord:
  # What channel types should the bot respond to.
  # Available values:
  # :text
  # :private
  # :voice
  # :group
  allowed_channel_types:
    - :text
    - :private
  # IDs of the admin users.
  # These users will have access to commands such as del_quote.
  administrators:
    - 128567958086615040 # nightycloud
  # IDs of the ban_appeals role and channel
  appeals_role: '436274219471339520'
  appeals_channel: '436273790465474561'
  # Name of the bot for some commands.
  bot_name: 'sweetie'
  # Should the bot autocorrect links?
  autocorrect_links: false
  # What replacements should the bot make?
  autocorrect_replacements:
    - ["trixiebooru.org", "derpibooru.org"]
    - ["www.derpibooru.org", "derpibooru.org"]
# Philomena-specific configuration.
booru:
  # URL base for URL things.
  url_base: "https://philomena.local"
  # Philomena API key to use.
  # Do not set it here, use PHILOMENA_API_KEY environment variable instead.
  api_key: ''
  # Filter to use in NSFW channels.
  nsfw_filter: 2
  # Filter to use in SFW channels.
  sfw_filter: 1
  # Everything filter.
  everything_filter: 2
  # Tags to hide, separated by adapter.
  hidden_tags:
    # Arrays are considered as AND conditions.
    # Use leading ! to indicate NOT.
    - [ grimdark, torture ]
    - [ grimdark, animal abuse]
    - [ gore, grotesque ]
    - [ foalcon, '!safe' ]
    - [ cub, '!safe' ]
    - kill yourself
  # No search tags
  no_search_tags:
    - tag_count.gt:200
# Any bots not defined here will not be created.
bots:
  # Example Discord configuration
  bot_id:
    # Account token
    # Do not set it here, use DISCORD_BOT_TOKEN environment variable instead.
    token: 'secret_token'
    # Account type. Valid values: :bot :user
    # Do not use this as a self-bot, it's against the Discord ToS.
    client_type: :bot
    # Whether the bot should ignore it's own messages
    ignore_self: true
    # Whether or not should the bot ignore other bots.
    ignore_bots: true
    # Whether or not to display the bot's version under "Playing".
    display_version: true
    # Title of the bot to display under "Playing".
    bot_title: 'Sweetie Bot'
